### ISSUE TITLE
test on linux

### ISSUE THREAD

**Issue by ngdream** [ngdream/H5assembler#5]

**Comment by Kashyap-Pandya** [comment]
download seems down.

**Comment by ngdream** [comment]
> download seems down.
Thank you for your comment
if you don't know how to use flex or bison you can have a version of the program written only in c++ here : https://github.com/ngdream/H5assembler-cpp

**Comment by ngdream** [comment]
if you have any recommendation  i'm here 😄

**Comment by Kashyap-Pandya** [comment]
can you elaborate bit more what you're looking help with? if it's a website i can help you with that. i should be free on this weekend can work on the website if that's what you're looking for :) cheers.

**Comment by ngdream** [comment]
any contribution is welcome 🔥 

here is the website repository: https://github.com/ngdream/H5A.github.io

**Comment by Kashyap-Pandya** [comment]
alright, i will work on the website in the weekend. you can assign it to me.

**Comment by Kashyap-Pandya** [comment]
Is there supposed to be documentation for your project ?i couldn't find it as of now so should i just remove or hide the link for now? something else kept me busy for awhile so couldn't work on this.

**Comment by Kashyap-Pandya** [comment]
Discord invite has expeired, please share the new link.

**Comment by ngdream** [comment]
> Is there supposed to be documentation for your project ?i couldn't find it as of now so should i just remove or hide the link for now? something else kept me busy for awhile so couldn't work on this.

For the moment it is the design of the site that concerns me the most

**Comment by ngdream** [comment]
i'am i'm writting the documentation

**Comment by Kashyap-Pandya** [comment]
> > Is there supposed to be documentation for your project ?i couldn't find it as of now so should i just remove or hide the link for now? something else kept me busy for awhile so couldn't work on this.
> 
> For the moment it is the design of the site that concerns me the most

i have finished the site, let me know if for mobile experience if you would rather have a hamburger menu for those 3 header links.

**Comment by Kashyap-Pandya** [comment]
can you please merge it and check? let me know if you find any bugs or want me to change somethings. should be able to work on the weekend.
